### PR TITLE
fix issue on mdbook config

### PR DESCRIPTION
**Pull request by Seasawher**
The current directory should not be specified as the src directory. This causes a problem where the `.git` directory is copied into the `book` directory.

### CODE REVIEW

**Comment by Seasawher** [comment]
artifact (pdf) : 

* https://github.com/leanprover-community/lean4-metaprogramming-book/actions/runs/8604421080

**Comment by Seasawher** [comment]
memo: expected out put of `$(grep ...)` command:

```txt
md/main/01_intro.md
md/main/02_overview.md
```

**Comment by Seasawher** [comment]
this PR also fix issue https://github.com/leanprover-community/lean4-metaprogramming-book/pull/121#discussion_r1447642044

**Comment by Julian** [comment]
Looks good to me I think. Thanks again!

**Pull request merged**
